### ISSUE TITLE
Add plugins to readme?

### ISSUE THREAD

**Issue by lorenmh** [karma-runner/karma-commonjs#45]
Hey guys, just noting an issue I encountered when trying to get karma-commonjs set up.  

I wasn't able to get karma-commonjs to work until I added 'karma-commonjs' to the plugins array in my karma configuration file:

```
plugins: [
      'karma-jasmine',
      'karma-chrome-launcher',
      'karma-firefox-launcher',
      'karma-commonjs'
    ]
```

Didn't see it anywhere in the readme though, only was able to figure this out from looking at https://github.com/karma-runner/karma/blob/master/test/client/karma.conf.js .

Could you guys add that to the README.md? For those of us new to karma and karma-commonjs.

Otherwise, works great, thanks!

**Comment by pkozlowski-opensource** [comment]
The problem here is that you had plugins listed manually. Check "Loading plugins" in http://karma-runner.github.io/0.13/config/plugins.html
